version: '3'
services:
  connector-export-git:
    build: ./export/git/
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_LOG_LEVEL=error
      - "EXPORT_FILE_CSV_DELIMITER=,"
    restart: always
